quiz/urls.py
from django.urls import path

from quiz.api.resourses import getQuestionList, QuestionStatForm, ScoreChart, UpdateQuestionForm, ToggleTestActive,\
    AddQuestionForm
from quiz.views import MyTestsListView, AllTestsListView, TestDetailView, TestCreateView, \
    DeleteTestView, TestPublicView, CommentCreateView, QuestionList, EndTestView, DeleteCommentView


urlpatterns = [
    path('mytests/', MyTestsListView.as_view(), name='my_tests'),
    path('alltests/', AllTestsListView.as_view(), name='all_tests'),
    path('create/test', TestCreateView.as_view(), name='create_test'),
    path('create/comment/<int:pk>/', CommentCreateView.as_view(), name='create_comment'),
    path('delete/test/<int:pk>/', DeleteTestView.as_view(), name='delete_test'),
    path('delete/comment/<int:pk>/', DeleteCommentView.as_view(), name='delete_comment'),
    path('detail/<int:pk>/', TestDetailView.as_view(), name='detail_test'),
    path('detail/public/<int:pk>/', TestPublicView.as_view(), name='detail_public_test'),
    path('<int:pk>/endquiz', EndTestView.as_view(), name='end_quiz'),
    path('take/<int:pk>/', QuestionList.as_view(), name='take_quiz'),
    path('ajax/<int:pk>/questions', getQuestionList.as_view(), name="getQuestions"),
    path("ajax/<int:qpk>/response", QuestionStatForm.as_view(), name="QuestionStatForm"),
    path("ajax/<int:pk>/add", AddQuestionForm.as_view(), name="addQuestionForm"),
    path("ajax/test/<int:pk>/score_chart", ScoreChart.as_view(), name="score_chart"),
    path('ajax/<int:tpk>/update/question/<int:qpk>', UpdateQuestionForm.as_view(), name='update_question'),
    path('ajax/<int:pk>/activate', ToggleTestActive.as_view(), name='activate_quiz'),
]

test_platform/urls.py
from django.contrib import admin
from django.urls import path, include
from quiz.views import IndexTemplateView
from test_platform import settings
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('', IndexTemplateView.as_view(), name='index'),
    path('admin/', admin.site.urls),
    path('quiz/', include(('quiz.urls', 'quiz'))),
    path('authenticate/', include(('authenticate.urls', 'authenticate'))),
    path('user/', include(('accounts.urls', 'user'))),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

quiz/models.py
import bleach
from django.db import models
from django.urls import reverse
from authenticate.models import UserProfile


class Test(models.Model):
    name = models.CharField(max_length=100, blank=False, default="Sample Test")
    description = models.TextField(max_length=500, null=True, blank=True)
    owner = models.ForeignKey(
        UserProfile, related_name="tests", null=True, on_delete=models.SET_NULL
    )
    created_on = models.DateTimeField(auto_now_add=True)
    modified_on = models.DateTimeField(auto_now=True)
    is_active = models.BooleanField(default=False)
    published_on = models.DateTimeField(null=True)

    def score(self):
        return self.attempts.all()

    def get_attempts(self):
        return self.attempts.all().count()

    def get_question_count(self):
        return self.questions.all().count()

    def get_absolute_url(self):
        return reverse("quiz:detail_test", args=[self.id])

    def get_test_detail_url(self):
        return reverse("quiz:detail_public_test", args=[self.id])

    def __str__(self):
        return self.name


class Question(models.Model):
    test = models.ForeignKey(Test, related_name="questions", on_delete=models.CASCADE)
    question = models.TextField(max_length=2000, blank=False)
    wrong_answer_1 = models.CharField(max_length=500, blank=False, null=False)
    wrong_answer_2 = models.CharField(max_length=500, blank=True, null=True)
    wrong_answer_3 = models.CharField(max_length=500, blank=True, null=True)
    correct_answer = models.CharField(max_length=500, blank=True, null=True)
    created_on = models.DateTimeField(auto_now_add=True)
    is_active = models.BooleanField(default=True)

    def get_update_url(self):
        return reverse(
            "quiz:update_question", kwargs={"tpk": self.test.id, "qpk": self.id}
        )

    def __str__(self):
        return self.question

    class Meta:
        verbose_name_plural = 'Questions'
        ordering = ['-created_on']


class TestStat(models.Model):
    test = models.ForeignKey(
        Test, related_name="attempts", null=True, on_delete=models.SET_NULL
    )
    candidate = models.ForeignKey(
        UserProfile, related_name="teststats", on_delete=models.CASCADE
    )
    has_completed = models.BooleanField(default=False)
    date_taken = models.DateTimeField(auto_now_add=True)
    score = models.DecimalField(max_digits=9, decimal_places=2, null=True)

    def get_total_attempts(self):
        return QuestionStat.objects.filter(
            question__in=self.test.questions.all(), candidate=self.candidate
        ).count()

    def get_wrong_response_count(self):
        if self.has_completed:
            return (
                QuestionStat.objects.filter(
                    question__in=self.test.questions.all(),
                    candidate=self.candidate,
                    is_correct=False,
                    response__isnull=False,
                )
                    .exclude(response__exact="")
                    .count()
            )
        return None

    def get_correct_response_count(self):
        if self.has_completed:
            return QuestionStat.objects.filter(
                question__in=self.test.questions.all(),
                candidate=self.candidate,
                is_correct=True,
            ).count()
        return None

    def save(self, *args, **kwargs):
        if self.has_completed:
            self.score = (QuestionStat.objects.filter(
                question__in=self.test.questions.all(),
                candidate=self.candidate,
                is_correct=True,
            ).count() / self.test.questions.all().count() * 100)
        super(TestStat, self).save(*args, **kwargs)

    def __str__(self):
        return "{}-{}".format(self.test, "Stat")


class QuestionStat(models.Model):
    question = models.ForeignKey(
        Question, related_name="question_history", null=True, on_delete=models.SET_NULL
    )
    candidate = models.ForeignKey(
        UserProfile, related_name="questionstat", null=True, on_delete=models.CASCADE
    )
    response = models.CharField(max_length=500, blank=True)
    is_correct = models.BooleanField(default=False)

    def save(self, *args, **kwargs):
        if self.response == bleach.clean(self.question.correct_answer):
            self.is_correct = True
        super(QuestionStat, self).save(*args, **kwargs)

    # def __str__(self):
    #     return "{}-{}".format(self.question.question, "stat")


class Comment(models.Model):
    test = models.ForeignKey(Test, related_name="comments", on_delete=models.CASCADE)
    candidate = models.ForeignKey(
        UserProfile, related_name="candidate_comments", on_delete=models.CASCADE
    )
    message = models.CharField(max_length=2000)
    created_on = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.message

quiz/forms.py
from django.forms import ModelForm
from .models import Test, Question, Comment, QuestionStat


class AddQuizForm(ModelForm):
    class Meta:
        model = Question
        fields = [
            "question",
            "wrong_answer_1",
            "wrong_answer_2",
            "wrong_answer_3",
            "correct_answer",
        ]


class AddTestForm(ModelForm):

    class Meta:
        model = Test
        fields = ["name", "description"]


class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ['message']


class AddAnswerForm(ModelForm):
    class Meta:
        model = QuestionStat
        fields = ['response']

quiz/views.py
from django.contrib import messages
from django.contrib.auth.mixins import UserPassesTestMixin
from django.http import HttpResponseRedirect
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views import View
from django.views.generic import TemplateView, ListView, CreateView, DetailView, DeleteView
from quiz.filters import TestFilter
from quiz.forms import AddTestForm, AddQuizForm, CommentForm
from quiz.models import Test, Question, TestStat, Comment


class IndexTemplateView(TemplateView):
    template_name = 'index.html'


class TestCreateView(CreateView, UserPassesTestMixin):
    """
    User create new Test object.
    """
    http_method_names = ['get', 'post']
    form_class = AddTestForm
    template_name = 'quiz/create_test.html'
    success_url = reverse_lazy('quiz:my_tests')

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super().form_valid(form)

    def test_func(self):
        request_obj = Test.objects.get(pk=self.kwargs.get('pk'))
        if self.request.user == request_obj.user:
            return True


class MyTestsListView(ListView, UserPassesTestMixin):
    """
    Current user list of tests
    """
    model = Test
    template_name = 'quiz/my_tests.html'
    context_object_name = 'tests'

    def get_queryset(self):
        queryset = super().get_queryset().filter(owner=self.request.user)
        return queryset

    def test_func(self):
        request_obj = Test.objects.get(pk=self.kwargs.get('pk'))
        if self.request.user == request_obj.owner:
            return True


class AllTestsListView(ListView):
    """
    List of all tests with filtering and sorting objects
    """
    model = Test
    template_name = 'quiz/all_tests.html'
    context_object_name = 'tests'
    test_filter = None

    def get_queryset(self):
        queryset = super().get_queryset().filter(is_active=True)
        qs = self.model.objects.filter(is_active=True)
        self.test_filter = TestFilter(self.request.GET, queryset=qs)
        date_sort_str = self.request.GET.get('date')
        passes = self.request.GET.get('passes')
        if date_sort_str:
            queryset = queryset.order_by(date_sort_str)
            return queryset
        if passes is not None:
            teststat = TestStat.objects.filter(has_completed=True)
            if passes == '1':
                return queryset.filter(attempts__in=teststat, owner=self.request.user)
            return queryset.exclude(attempts__in=teststat)
        return self.test_filter.qs

    def get_context_data(self, object_list=None, **kwargs):
        context = super().get_context_data(object_list=None, **kwargs)
        context.update({'filter': self.test_filter})
        return context


class TestDetailView(UserPassesTestMixin, DetailView):
    """
    Detail of test for current user with ability to add questions
    """
    model = Test
    template_name = 'quiz/detail_test.html'
    context_object_name = 'test'

    def get_context_data(self, object_list=None, **kwargs):
        context = super().get_context_data(object_list=None, **kwargs)
        context.update({'questions': self.object.questions.all(),
                        'question_form': AddQuizForm})
        return context

    def test_func(self):
        request_obj = Test.objects.get(pk=self.kwargs.get('pk'))
        if self.request.user == request_obj.owner or self.request.user.is_superuser:
            return True


class DeleteTestView(DeleteView, UserPassesTestMixin):
    model = Test
    http_method_names = ['post']

    def get_success_url(self):
        return reverse_lazy('quiz:my_tests')

    def post(self, request, *args, **kwargs):
        self.queryset = self.get_object()
        self.queryset.delete()
        success_url = self.get_success_url()
        return HttpResponseRedirect(success_url)

    def test_func(self):
        if self.request.user == self.queryset.owner:
            return True


class DeleteCommentView(DeleteView, UserPassesTestMixin):
    model = Comment
    http_method_names = ['post']

    def get_success_url(self, **kwargs):
        return str(self.request.META.get('HTTP_REFERER'))

    def post(self, request, *args, **kwargs):
        self.queryset = self.get_object()
        self.queryset.delete()
        success_url = self.get_success_url()
        return HttpResponseRedirect(success_url)

    def test_func(self):
        if self.request.user == self.queryset.candidate:
            return True


class TestPublicView(DetailView):
    """
    Detail of test for all users with ability to add comments
    """
    model = Test
    template_name = 'quiz/public_detail_test.html'
    context_object_name = 'test'

    def get_context_data(self, object_list=None, **kwargs):
        user_teststat = None
        context = super().get_context_data(object_list=None, **kwargs)
        test = Test.objects.get(pk=self.kwargs.get('pk'))
        if self.request.user.is_authenticated:
            try:
                user_teststat = TestStat.objects.get(test=test, candidate=self.request.user)
            except:
                user_teststat = None
        context.update({'comments': self.object.comments.all(),
                        'comment_form': CommentForm,
                        'user_teststat': user_teststat})
        return context


class CommentCreateView(UserPassesTestMixin, CreateView):
    """
    User create new comment object.
    """
    form_class = CommentForm
    request_obj = None

    def form_valid(self, form):
        form.instance.candidate = self.request.user
        form.instance.test = self.request_obj
        return super().form_valid(form)

    def get_success_url(self):
        return str(self.request.META.get('HTTP_REFERER'))

    def test_func(self):
        self.request_obj = Test.objects.get(pk=self.kwargs.get('pk'))
        return True


class QuestionList(ListView):
    """
    List of all questions
    """
    model = Question
    template_name = 'quiz/take_quiz.html'
    context_object_name = 'questions'

    def get_queryset(self):
        queryset = super().get_queryset().filter(test=self.kwargs.get('pk'))
        return queryset

    def get_context_data(self, object_list=None, **kwargs):
        context = super().get_context_data(object_list=None, **kwargs)
        test = Test.objects.get(pk=self.kwargs.get('pk'))
        num_of_questions = Question.objects.filter(test=self.kwargs.get('pk')).count()
        teststat, created = TestStat.objects.get_or_create(
            test=test, candidate=self.request.user
        )
        has_completed = teststat.has_completed
        if teststat.score:
            score = round(teststat.score, 1)
        else:
            score = 0
        context.update({'num_questions': range(num_of_questions),
                        'score': score,
                        "testno": test.id,
                        "has_completed": has_completed, })
        return context


class EndTestView(UserPassesTestMixin, View):
    request_obj = None

    def post(self, request, *args, **kwargs):
        messages.error(request, 'You finished with that quiz')
        self.request_obj.has_completed = True
        self.request_obj.save()
        return redirect(self.request.META.get('HTTP_REFERER'))

    def test_func(self):
        self.request_obj, created = TestStat.objects.get_or_create(
            test=Test.objects.get(pk=self.kwargs.get('pk')), candidate=self.request.user.id
        )
        return True

templates/quiz/add_question.html
<div id="modal1" class="modal modal-fixed-footer">
    <form class="ajax-question-form" action="." data-url="{% url 'quiz:addQuestionForm' pk=test.pk %}" data-method="POST">
        <div class="modal-content" style="padding:0%">
        <nav class="website-theme">
                <div class="nav-wrapper">
                    <div class="left col s8 m5 l5 grey-text text-darken-4" style="margin-left:2%">
                        <ul>
                            <li style="font-size:1.3rem">Add Question</li>
                        </ul>
                    </div>
                    <div class="col s4 m7 l7">
                        <ul class="right">
                            <li><a href="#!"><i class="modal-action modal-close material-icons red-text text-accent-4">clear</i></a></li>
                        </ul>
                    </div>
                </div>
            </nav>
            <div class="row" style="padding:2%">
                <div class="col s12">
                    <div class="input_field">
                        {%csrf_token%}
                        {{ question_form.as_p }}
                    </div>
                </div>
            </div>
        </div>
        <div class="modal-footer">
            <button type="submit" id="questionSaveButton" class="waves-effect waves-green btn green">Add</button>
        </div>
    </form>
</div>

templates/quiz/create_test.html
{% extends 'base.html' %}

{% load widget_tweaks %}
{% block title%}<title>Create test</title>{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-sm-12">
            <h1>Create quiz</h1>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-6 col-sm-offset-3">
            <p class="text-center">Create name for your quiz and write some words about it</p>
            <form method="post" id="CreateTestForm">
                {% csrf_token %}
                {% if form.errors %}
                <div class="row">
                    <div class="col-sm-6">
                        <ul><li>Please input valid data</li>
                        </ul>
                    </div>
                </div>
                {% endif %}
                <label>Name your quiz:</label>{% render_field form.name class="input-lg form-control" %}
                <label>Description:</label>{% render_field form.description class="input-lg form-control" %}
                <input type="submit" class="col-xs-12 btn btn-primary btn-load btn-lg" data-loading-text="Create quiz.." value="Create quiz">
            </form>
        <button type="button" class="btn btn-outline-danger">
                    <a class="nav-link" href="{% url 'quiz:my_tests' %}" style="color: red">
                        Cancel</a></button>
        </div><!--/col-sm-6-->
    </div><!--/row-->
</div>
{% endblock content %}

templates/quiz/detail_test.html
{% extends 'base.html' %}

{% load widget_tweaks %}
{% load humanize %}
{% block head %}
    <link href="https://cdn.jsdelivr.net/gh/gitbrent/bootstrap4-toggle@3.6.1/css/bootstrap4-toggle.min.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/gh/gitbrent/bootstrap4-toggle@3.6.1/js/bootstrap4-toggle.min.js"></script>
{% endblock %}
{% block title%}<title>Test detail</title>{% endblock %}

{% block content %}
{% include 'quiz/add_question.html' %}
<div style="margin: 2%">
     <div class="row" style="margin: 1%">
        <div class="col">
          <div class="card">
            <div class="card-body">
                {% if not test.is_active %}
                    <form method="post" action="{% url 'quiz:delete_test' test.pk %}">
                        {% csrf_token %}
                        <button class="btn-floating red right deleteConfirm" type="submit" style="position: absolute; right: 0"><i class="material-icons">delete_forever</i></button>
                    </form>
                {% endif %}
              <h5 class="card-title">{{test.name}}</h5>
                <p class="card-text">Description:
                    {{ test.description }}</p>
              <h6 class="card-subtitle mb-2 text-muted">Added on: {{ test.created_on|naturaltime }}</h6>
              <p class="card-text">This quiz can pass any users {{ test.num_passes }} times</p>
               <div class="col s12 l2">
			        <button style="font-size:0.8rem; margin: 1%" class="btn btn-toggleactive {% if test.is_active %}green{% else %}red{% endif %}">
				        <div class="switch">
					        Active
					        <label>
                                <input class="toggleactive" type="checkbox" {% if test.is_active %}checked{% endif %}>
                                <span class="lever"></span>
					        </label>
				        </div>
			        </button>
		        </div>
            </div>
          </div>
        </div>
      </div>
    <div style="padding: 1%">
		<div>
			<div class="col s12 l12" style="padding: 1%">
				<span class="left">
					<h5>Questions</h5>
				</span>
				<span class="right">
					<div class="col s12 l2 right">
						<a id="add-new-question" class="waves-effect waves-light btn-floating pulse red center" href="#" onclick="$('#modal1').modal('open');" {% if test.publish %}disabled{% endif %}><i class="material-icons">note_add</i></a>
					</div>
				</span>
			</div>
		</div>
    <br>
		<div id="questionList">
			<!-- to be filled with questions -->
		</div>
	</div>
</div>
{#    <div class="card" style="padding: 1%">#}
{#        <div class="question">#}
{#            <h3 class="title-question">Questions | ({{ questions.count }})</h3>#}
{#                <div class="text-center">#}
{#                    <a id="add-new-question" class="waves-effect waves-light btn-floating pulse red center" href="#" onclick="$('#modal1').modal('open');" {% if test.publish %}disabled{% endif %}>#}
{#                        <i class="material-icons">note_add</i></a>#}
{#                </div>#}
{##}
{#<ul class="list-group">#}
{#    {% for question in questions %}#}
{#        <li class="list-group-item d-flex justify-content-between align-items-center">#}
{#            {{ question.question|linebreaks }}#}
{#        <span>#}
{#        <a href="" data-toggle="modal" data-target="#Update">#}
{#       <i class="far fa-edit" ></i>Update question</a>#}
{#        <form method="post" action="{% url 'quiz:delete_question' question.pk %}">#}
{#            {% csrf_token %}#}
{#            <button type="submit" class="btn btn-danger">Delete</button>#}
{#        </form>#}
{#    </span>#}
{#  </li>#}
{#    {% endfor %}#}
{#</ul>#}

{% endblock content %}

{% block scripts %}
<script>
	$(document).ready(function() {
	    $("#questionList").on('mouseenter', '.questioncard', function() {
			$(this).toggleClass('z-depth-4');
		});
		$("#questionList").on('mouseleave', '.questioncard', function() {
			$(this).toggleClass('z-depth-4');
		});
	    (function () {
			$("#id_question").parent().append('<div id="quill-editor"></div>');
			$("#id_question").prop('hidden', true).prop("required", false);
			var quill = new Quill('#quill-editor', {
				modules: {
					toolbar: [
						['bold', 'italic', 'underline'],
						['link', 'blockquote', 'code-block',],
						[{ list: 'ordered' }, { list: 'bullet' }],
            			[{ 'script': 'sub'}, { 'script': 'super' }],
					]
				},
				placeholder: 'Write Question...',
				theme: 'snow',
			});
		})();
		$('.modal').modal();
		let is_active = "True" === "{{ test.is_active }}";
		$.ajax({
			method: 'GET',
			url: "{% url 'quiz:getQuestions' pk=test.pk %}",
			success: handleFormSuccess,
			error: handleFormError
		});
		$(".toggleactive").click(function(e) {
			$.ajax({
				method: 'PUT',
				url: "{% url 'quiz:activate_quiz' pk=test.pk %}",
				success: function(data, textStatus, jqXHR) {
					console.log(data.active);
					if(data.active === true) {
						$(".btn-toggleactive").toggleClass("red").toggleClass("green")
					} else {
						$(".btn-toggleactive").toggleClass("green").toggleClass("red");
					}
					new PNotify({
						title:'Done!',
						type: 'success'
					});
				},
				error: function(jqXHR, textStatus, errorThrown) {
					$(".toggleactive").prop('checked', !$(".toggleactive").prop('checked'));
					new PNotify({
						title:'Operation Failed!',
						type: 'error',
                        text: jqXHR.responseJSON['message'],
					});
				}
			});
		});
		$('#add-new-question').click(function(event) {
				console.log("Add Question");
				$('.ajax-question-form').trigger("reset");
				$(".ql-editor").empty();
				$("#modal-title").html("Add Question");
				$("#questionSaveButton").html("Add Question");
				$('.ajax-question-form').attr('data-url',"{% url 'quiz:addQuestionForm' pk=test.pk %}");
				$('.ajax-question-form').attr('data-method','POST');
		});
		$("#questionList").on('click', '.updateQuestion', function(event) {
			event.preventDefault();
			console.log("Update Question");
			var $thisURL = $(this).attr('data-url');
			$.ajax({
				method: 'GET',
				url: $thisURL,
				success: function(data, textStatus, jqXHR) {
					console.log(data);
					$('#modal1').modal('open');
					$(".ql-editor").html(data.question);
					$("#id_wrong_answer_1").val(data.wrong_answer_1);
					$("#id_wrong_answer_2").val(data.wrong_answer_2);
					$("#id_wrong_answer_3").val(data.wrong_answer_3);
					$("#id_correct_answer").val(data.correct_answer);
					$('.ajax-question-form').attr('data-url',$thisURL);
					$('.ajax-question-form').attr('data-method','PUT');
					$("#modal-title").html("Edit Question");
					$("#questionSaveButton").prop("disabled", is_active).html("Edit Question");
				},
				error: function(jqXHR, textStatus, errorThrown) {
					console.log(errorThrown);
				}
			});
		});
		$('.ajax-question-form').submit(function(event) {
			event.preventDefault();
			$("#id_question").val($(".ql-editor").html());
			var $formData = $(this).serialize();
			var $methodType = $('.ajax-question-form').attr('data-method');
			var $thisURL = $('.ajax-question-form').attr('data-url');
			console.log($formData);
			$.ajax({
				method: $methodType,
				url: $thisURL,
				data: $formData,
				success: handleFormSuccess,
				error: handleFormError,
			});
		});
		$("#questionList").on('submit','.deleteQuestion', function(event) {
			event.preventDefault();
			var $thisURL = $(this).attr('data-url');
			console.log($thisURL);
			$.ajax({
				method: 'DELETE',
				url: $thisURL,
				success: handleFormSuccess,
				error: handleFormError,
			});
		});
		function handleFormSuccess(data, textStatus, jqXHR) {
			new PNotify({
				title: 'Question Updated!',
				type: 'success'
			});
			console.log(data);
			$('.ajax-question-form').trigger("reset");
			$('#modal-close').click();
			refreshQuestionList(data);
		}
		function handleFormError(jqXHR, textStatus, errorThrown) {
			new PNotify({
				title: 'Oops! Error',
				type: 'error'
			});
			console.log(errorThrown);
		}
		function refreshQuestionList(data) {
			$("#questionList").empty();
			data.forEach(function(question, index) {
				var content = `<div class="card horizontal questioncard" style="padding:1%;margin:1.5%"><div><span class="left">${question.question}</span>`;

				if(is_active === false) {
					content += `<form class="deleteQuestion" data-url="${question.update_url}"><button type="submit" class="btn-floating waves-effect red right z-depth-3" style="margin-left:1%"><i class="material-icons">delete_forever</i></button></form>`;
				}
				content += `<a class="btn-floating waves-effect red right z-depth-3 updateQuestion" data-url="${question.update_url}" style="margin-left:1%" ><i class="material-icons">mode_edit</i></a></div></div>`;
				$("#questionList").append(content);
			});
		}
	})
</script>
{% endblock scripts %}

templates/quiz/public_detail_test.html
{% extends 'base.html' %}

{% load widget_tweaks %}
{% load humanize %}
{% block title%}<title>Test detail</title>{% endblock %}

{% block content %}
<div style="margin: 2rem">
    <div class="row">
        <div class="card col s12 l12">
            <div class="card-content">
                <div class="row">
                    <div class="col s8 l4 offset-s2">
                        <h3 class="card-title grey-text text-darken-4" style="font-size:2.2rem">{{ test.name }}</h3>
                        <h6 class="card-title grey-text text-darken-4" style="font-size:2.2rem">by {{ test.owner.username }}</h6>
                        <span class=" grey-text text-darken-2">{{ test.description}}</span>
                    </div>
                    <div class="col s6 l2 center-align">
                        <h4 class="card-title grey-text text-darken-4">{{ test.get_attempts }}</h4>
                        <span class=" grey-text text-darken-2">Total Submissions</span>
                    </div>
                    <div class="col s6 l2 center-align">
                        <h4 class="card-title grey-text text-darken-4">{{ test.get_question_count }}</h4>
                        <span class=" grey-text text-darken-2">Number of Questions</span>
                    </div>
                    <div class="col s6 l2 center-align">
                        <h4 class="card-title grey-text text-darken-4">{{ test.created_on|date }}</h4>
                        <span class=" grey-text text-darken-2">Published Date</span>
                    </div>
                </div>
                <div class="card-action">
                    <div class="row">
                    <div class="col s12 l6 right">
                        <a href="{% url 'quiz:take_quiz' pk=test.pk %}" class="btn blue right"{% if not request.user.is_authenticated %}disabled{% endif %}>
                        {% if user_teststat %}
                        {% if user_teststat.has_completed %}
                            Result
                        {% else %}
                            Continue
                        {% endif %}
                        {% else %}
                            Take Quiz
                        {% endif %}
                        </a>
                    </div>
                </div>
              </div>
            </div>
        </div>
    </div>
    <div class="comments">
        <h3 class="title-question">Comments | ({{ comments.count }})</h3>
    </div>
<div class="row">
        <div class="col s12">
             <ul class="collection" id="comment_section">
                {% for comment in comments %}
                <li class="collection-item">
                    <span class="title">{{ comment.candidate.username }}</span><br>
                    {{ comment.created_on|naturaltime }}<br>
                    {{ comment.message }}
                    {% if comment.candidate == request.user %}
                        <form class="secondary-content" method="post" action="{% url 'quiz:delete_comment' pk=comment.pk %}">
                            {% csrf_token %}
                            <button type="submit" style="position: absolute; right: 0"><i class="material-icons red-text">delete</i></button>
                         </form>
                    {% endif %}
                </li>
                {% endfor %}
                {% if request.user.is_authenticated %}
                <li class="valign-wrapper row" style="margin: 1rem">
                    <div class="input-field col s11">
                        <form action="{% url 'quiz:create_comment' test.pk %}" method="post">
                            {% csrf_token %}
                            <p><label for="id_response">Add your comment</label></p>
                            {% render_field comment_form.message class="input-lg form-control" %}
                            <button class="waves-effect waves-light btn col s1" type="submit">Comment</button>
                        </form>
                    </div>
                </li>
                {% endif %}
              </ul>
        </div>
    </div>
</div>
{% endblock content %}